spring:
  profiles:
    active:
      native
    ## profil native czyta konfigurację z lokalnych plików, an nie z gita, w tym przypadku z podfolderu configurations określonego poniżej
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
